# Generated by Django 2.1.2 on 2018-12-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20181222_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='color_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='カラーコード'),
        ),
        migrations.AddField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='駅コード'),
        ),
    ]
