# Generated by Django 2.1.2 on 2018-12-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Companies',
        ),
        migrations.RenameModel(
            old_name='Route',
            new_name='Routes',
        ),
        migrations.RenameModel(
            old_name='Station',
            new_name='Stations',
        ),
    ]
