# Generated by Django 2.1.2 on 2018-12-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20181222_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
