# Generated by Django 2.0.2 on 2019-01-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20181222_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='条件名')),
                ('input_type', models.IntegerField(choices=[(11, 'select to select befor'), (19, 'select to select after'), (20, 'select box'), (30, 'check box'), (40, 'radio box')], verbose_name='inputのtype属性')),
                ('input_name', models.CharField(max_length=10, verbose_name='inputのname属性')),
                ('sort', models.IntegerField(verbose_name='ソート順')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='グループ名')),
                ('sort', models.IntegerField(verbose_name='ソート順')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='値の名称')),
                ('code', models.CharField(max_length=20, verbose_name='コード')),
                ('input_name', models.CharField(max_length=10, verbose_name='inputのname属性')),
                ('is_default', models.IntegerField(default=0, verbose_name='デフォルト設定')),
                ('sort', models.IntegerField(verbose_name='ソート順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.Condition', verbose_name='条件名')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.ConditionsGroup', verbose_name='グループ名'),
        ),
    ]
