# Generated by Django 2.0.2 on 2019-01-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20181222_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='条件名')),
                ('input_type', models.IntegerField(choices=[(10, 'select to select'), (20, 'check box'), (30, 'radio box')], verbose_name='inputのtype属性')),
                ('sort', models.IntegerField(verbose_name='ソート順')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='グループ名')),
                ('sort', models.IntegerField(verbose_name='ソート順')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='値の名称')),
                ('input_name', models.CharField(max_length=10, verbose_name='inputのname属性')),
                ('code', models.CharField(max_length=20, verbose_name='駅コード')),
                ('is_default', models.IntegerField(default=0, verbose_name='デフォルト設定')),
                ('sort', models.IntegerField(verbose_name='ソート順')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.Condition', verbose_name='条件名')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.ConditionsGroup', verbose_name='グループ名'),
        ),
    ]
