# Generated by Django 2.0.2 on 2019-01-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20190119_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConditionsValue',
            new_name='ConditionValue',
        ),
    ]
