# Generated by Django 2.0.2 on 2019-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20190120_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='使用中'),
        ),
        migrations.AddField(
            model_name='conditionsgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='使用中'),
        ),
    ]
